"""
Cell template system for notebook generation.
"""

import json
from typing import Dict, List, Any, Optional, Callable
from dataclasses import dataclass
from enum import Enum
import structlog

logger = structlog.get_logger()

class CellType(str, Enum):
    """Jupyter notebook cell types."""
    CODE = "code"
    MARKDOWN = "markdown"
    RAW = "raw"

@dataclass
class CellTemplate:
    """Template for generating notebook cells."""
    
    name: str
    cell_type: CellType
    template: str  # Template string with placeholders
    description: Optional[str] = None
    tags: List[str] = None
    variables: List[str] = None  # List of template variables
    
    def __post_init__(self):
        if self.tags is None:
            self.tags = []
        if self.variables is None:
            self.variables = []
    
    def render(self, context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Render the template with given context.
        
        Args:
            context: Variables to substitute in template
            
        Returns:
            Jupyter notebook cell dictionary
        """
        try:
            # Substitute variables in template
            rendered_source = self.template.format(**context)
            
            # Split into lines for Jupyter format
            source_lines = rendered_source.split('\n')
            if source_lines and not source_lines[-1]:
                source_lines.pop()  # Remove empty last line
            
            # Add newlines to all but last line
            source = [line + '\n' for line in source_lines[:-1]]
            if source_lines:
                source.append(source_lines[-1])
            
            cell = {
                "cell_type": self.cell_type.value,
                "metadata": {
                    "template": self.name,
                    "tags": self.tags
                },
                "source": source
            }
            
            # Add execution fields for code cells
            if self.cell_type == CellType.CODE:
                cell["execution_count"] = None
                cell["outputs"] = []
            
            return cell
        
        except KeyError as e:
            raise ValueError(f"Missing template variable: {e}")
        except Exception as e:
            raise ValueError(f"Template rendering failed: {e}")

class CellTemplateLibrary:
    """Library of cell templates for different tool types."""
    
    def __init__(self):
        """Initialize with built-in templates."""
        self.templates: Dict[str, CellTemplate] = {}
        self._load_builtin_templates()
    
    def _load_builtin_templates(self):
        """Load built-in cell templates."""
        
        # Header template
        self.add_template(CellTemplate(
            name="header",
            cell_type=CellType.MARKDOWN,
            template="""# {title}

{description}

**Generated by:** notebook-sandbox  
**Workflow:** {workflow_name}  
**Created:** {timestamp}

---
""",
            description="Notebook header with title and metadata",
            tags=["header", "metadata"],
            variables=["title", "description", "workflow_name", "timestamp"]
        ))
        
        # Setup imports template
        self.add_template(CellTemplate(
            name="setup_imports",
            cell_type=CellType.CODE,
            template="""# Setup and imports
import pandas as pd
import numpy as np
import json
from datetime import datetime
from typing import Dict, List, Any, Optional

# Configure pandas display options
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

print("Environment setup complete")""",
            description="Standard imports and setup",
            tags=["setup", "imports"],
            variables=[]
        ))
        
        # SQL query template
        self.add_template(CellTemplate(
            name="sql_query",
            cell_type=CellType.CODE,
            template="""# {step_name}: {description}
import sqlalchemy as sa
from sqlalchemy import create_engine, text

# Database connection
engine = create_engine('{connection_string}')

# Execute query
query = '''
{sql_query}
'''

try:
    with engine.connect() as conn:
        result = conn.execute(text(query))
        
        # Convert to DataFrame if SELECT query
        if query.strip().upper().startswith('SELECT'):
            df = pd.DataFrame(result.fetchall(), columns=result.keys())
            print(f"Query returned {{len(df)}} rows")
            display(df.head())
        else:
            rows_affected = result.rowcount
            print(f"Query executed successfully. Rows affected: {{rows_affected}}")
            
except Exception as e:
    print(f"Query execution failed: {{e}}")
    raise""",
            description="Execute SQL query and display results",
            tags=["sql", "database", "query"],
            variables=["step_name", "description", "connection_string", "sql_query"]
        ))
        
        # API request template
        self.add_template(CellTemplate(
            name="api_request",
            cell_type=CellType.CODE,
            template="""# {step_name}: {description}
import requests
import json

# API request configuration
url = '{url}'
method = '{method}'
headers = {headers}
data = {data}

try:
    # Make request
    if method.upper() == 'GET':
        response = requests.get(url, headers=headers, params=data)
    elif method.upper() == 'POST':
        response = requests.post(url, headers=headers, json=data)
    elif method.upper() == 'PUT':
        response = requests.put(url, headers=headers, json=data)
    elif method.upper() == 'DELETE':
        response = requests.delete(url, headers=headers)
    else:
        raise ValueError(f"Unsupported HTTP method: {{method}}")
    
    # Check response
    response.raise_for_status()
    
    # Parse response
    try:
        result = response.json()
        print(f"API request successful. Status: {{response.status_code}}")
        print(f"Response keys: {{list(result.keys()) if isinstance(result, dict) else 'Not a dict'}}")
        
        # Display result (truncated if large)
        if isinstance(result, (dict, list)):
            if len(str(result)) > 1000:
                print("Response (truncated):")
                print(json.dumps(result, indent=2)[:1000] + "...")
            else:
                print("Response:")
                print(json.dumps(result, indent=2))
        else:
            print(f"Response: {{result}}")
            
    except json.JSONDecodeError:
        print(f"Response (text): {{response.text[:500]}}")
        result = response.text
        
except requests.RequestException as e:
    print(f"API request failed: {{e}}")
    raise""",
            description="Make HTTP API request and handle response",
            tags=["api", "http", "rest"],
            variables=["step_name", "description", "url", "method", "headers", "data"]
        ))
        
        # Python script template
        self.add_template(CellTemplate(
            name="python_script",
            cell_type=CellType.CODE,
            template="""# {step_name}: {description}

{code}""",
            description="Execute Python code",
            tags=["python", "script", "code"],
            variables=["step_name", "description", "code"]
        ))
        
        # Data transformation template
        self.add_template(CellTemplate(
            name="data_transform",
            cell_type=CellType.CODE,
            template="""# {step_name}: {description}

# Input data validation
if '{input_variable}' not in locals():
    raise ValueError("Input data '{input_variable}' is not available")

input_data = {input_variable}
print(f"Input data type: {{type(input_data)}}")

if isinstance(input_data, pd.DataFrame):
    print(f"Input DataFrame shape: {{input_data.shape}}")
    print(f"Columns: {{list(input_data.columns)}}")

# Data transformation
{transformation_code}

# Output validation
print(f"Output data type: {{type({output_variable})}}")
if isinstance({output_variable}, pd.DataFrame):
    print(f"Output DataFrame shape: {{{output_variable}.shape}}")
    print(f"Output columns: {{list({output_variable}.columns)}}")
    display({output_variable}.head())
elif isinstance({output_variable}, (list, dict)):
    print(f"Output preview: {{{output_variable}[:5] if isinstance({output_variable}, list) else {output_variable}}}")
else:
    print(f"Output value: {{{output_variable}}}")""",
            description="Transform data with validation",
            tags=["transform", "data", "validation"],
            variables=["step_name", "description", "input_variable", "transformation_code", "output_variable"]
        ))
        
        # Validation template
        self.add_template(CellTemplate(
            name="validation",
            cell_type=CellType.CODE,
            template="""# Validation: {description}

# Validation checks
validation_results = []

try:
    {validation_code}
    
    print("✅ All validations passed")
    
except AssertionError as e:
    print(f"❌ Validation failed: {{e}}")
    validation_results.append(f"FAILED: {{e}}")
    
except Exception as e:
    print(f"⚠️ Validation error: {{e}}")
    validation_results.append(f"ERROR: {{e}}")

# Summary
if validation_results:
    print("\\nValidation Summary:")
    for result in validation_results:
        print(f"  - {{result}}")
else:
    print("\\n✅ All validations completed successfully")""",
            description="Validate results and data",
            tags=["validation", "testing", "quality"],
            variables=["description", "validation_code"]
        ))
        
        # Summary template
        self.add_template(CellTemplate(
            name="summary",
            cell_type=CellType.MARKDOWN,
            template="""## Workflow Summary

**Workflow:** {workflow_name}  
**Completed:** {completion_time}  
**Total Steps:** {total_steps}  

### Results Summary
{results_summary}

### Next Steps
{next_steps}

---
*Generated by notebook-sandbox*""",
            description="Workflow summary and results",
            tags=["summary", "results", "conclusion"],
            variables=["workflow_name", "completion_time", "total_steps", "results_summary", "next_steps"]
        ))
        
        logger.info("Built-in cell templates loaded", count=len(self.templates))
    
    def add_template(self, template: CellTemplate):
        """Add a template to the library."""
        self.templates[template.name] = template
        logger.debug("Template added", name=template.name, type=template.cell_type.value)
    
    def get_template(self, name: str) -> Optional[CellTemplate]:
        """Get a template by name."""
        return self.templates.get(name)
    
    def list_templates(self, 
                      cell_type: Optional[CellType] = None,
                      tags: Optional[List[str]] = None) -> List[CellTemplate]:
        """
        List templates with optional filtering.
        
        Args:
            cell_type: Filter by cell type
            tags: Filter by tags (must have at least one matching tag)
            
        Returns:
            List of matching templates
        """
        templates = list(self.templates.values())
        
        if cell_type:
            templates = [t for t in templates if t.cell_type == cell_type]
        
        if tags:
            tag_set = set(tags)
            templates = [t for t in templates if tag_set.intersection(set(t.tags))]
        
        return templates
    
    def get_template_for_tool_type(self, tool_type: str) -> Optional[CellTemplate]:
        """
        Get the most appropriate template for a tool type.
        
        Args:
            tool_type: Type of tool (sql, api, script, etc.)
            
        Returns:
            Best matching template or None
        """
        # Direct mapping of tool types to template names
        tool_template_mapping = {
            "sql": "sql_query",
            "api": "api_request",
            "script": "python_script",
            "python": "python_script",
            "transform": "data_transform",
            "validation": "validation"
        }
        
        template_name = tool_template_mapping.get(tool_type.lower())
        if template_name:
            return self.get_template(template_name)
        
        # Fallback: look for templates with matching tags
        templates = self.list_templates(tags=[tool_type.lower()])
        if templates:
            return templates[0]
        
        # Default fallback
        return self.get_template("python_script")
    
    def render_template(self, 
                       template_name: str, 
                       context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Render a template with context.
        
        Args:
            template_name: Name of template to render
            context: Variables for template substitution
            
        Returns:
            Rendered cell dictionary
            
        Raises:
            ValueError: If template not found or rendering fails
        """
        template = self.get_template(template_name)
        if not template:
            raise ValueError(f"Template not found: {template_name}")
        
        return template.render(context)